# Generated by Django 4.1.2 on 2022-12-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0008_user_item_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Item_owned',
            new_name='item',
        ),
    ]
