# Generated by Django 4.1.3 on 2022-12-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0009_rename_item_owned_user_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item',
        ),
        migrations.AddField(
            model_name='messages',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_messages', to='auctionapp.item'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
