# Generated by Django 4.1.1 on 2022-12-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0010_remove_user_item_messages_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
