# Generated by Django 4.1.1 on 2022-12-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0012_item_last_bidder_item_owner'),
        ('auctionapp', '0012_remove_profile_username_foreign'),
    ]

    operations = [
    ]
